a = input('Digite algo: ')
print('O tipo primitivo desse valor e: ', type(a))
print('Só tem espaço?: ', a.isspace())
print('É numérico?: ', a.isnumeric())
print('E alfabetico?: ', a.isalpha())
print('E alphanumerico?: ', a.isalnum())
print('Está em maiusculo?: ', a.isupper())
print('Está em minuscula?: ', a.islower())
print('Está capitalizada?: ', a.istitle())
